# Generated by Django 5.2 on 2025-05-23 13:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='basic',
            name='information',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
